FROM nginx:alpine

ARG API_URL=http://localhost:8000

COPY app/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN sed -i "s|http://localhost:8000|${API_URL}|g" /usr/share/nginx/html/config.js

EXPOSE 80
