FROM nginx:alpine

ARG API_URL=http://localhost:8000
ARG AZURE_CLIENT_ID=__AZURE_CLIENT_ID__
ARG AZURE_TENANT_ID=__AZURE_TENANT_ID__

COPY app/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN sed -i "s|http://localhost:8000|${API_URL}|g" /usr/share/nginx/html/config.js && \
    sed -i "s|__AZURE_CLIENT_ID__|${AZURE_CLIENT_ID}|g; s|__AZURE_TENANT_ID__|${AZURE_TENANT_ID}|g" /usr/share/nginx/html/authConfig.js

EXPOSE 80
